---
name: autofix.ci
on:
  schedule: [cron: "0 0 */7 * *"]
  push: { branches: ["master"] }
  workflow_dispatch:
  pull_request:
concurrency: autofix-${{ github.ref }}
jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: kjanat/install-dprint@v1
      - uses: kjanat/install-shfmt@v1
      # - { uses: dtolnay/rust-toolchain@stable, with: { components: rustfmt } }
      - run: bun i -g tombi just sort-package-json svgo --trust

      - run: bash .github/scripts/dprint-update.sh
      - run: dprint fmt --allow-no-files --diff --excludes ".github"

      - uses: autofix-ci/action@v1
